name:  caller-work
on: 
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    uses: Sathishdevops38-githu-actions/roboshop-components/.github/workflows/reuse.yml@main
    with:
      my_variable: ${{ vars.MY_REPO_VARIABLE }}
    # if using secrets, you would add:
    # secrets:
    #   my_secret: ${{ secrets.MY_REPO_SECRET }}