name: roboshop ci
on: [push, workflow_dispatch]

# This replaces 'disableConcurrentBuilds()'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Global Environment Variables
env:
  COURSE: "Actions"
  PROJECT: "roboshop"
  COMPONENT: "catalogue"
  ACC_ID: "441700732169"
  APP_VERSION: ${{ github.sha }} # Pro-tip: Using the commit hash as a version

jobs:
  build:
    runs-on: ubuntu-latest
    # This replaces 'timeout(time: 10, unit: 'MINUTES')'
    timeout-minutes: 10
    steps:
      - name: Print Version
        run: echo "Deploying $COMPONENT for $PROJECT, $ACC_ID"